// <auto-generated />
using System;
using IngApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IngApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220012019_AddOfferEntities")]
    partial class AddOfferEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngApp.Domain.Entities.Auth.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ClientIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Kyc.KycAttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<bool>("DefaultRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KycAttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Kyc.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("KycAttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDeleted");

                    b.HasIndex("UserId", "KycAttributeDefinitionId", "IsDeleted");

                    b.ToTable("UserDocuments", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Menus.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("RequiredPermissionCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "DashboardOutlined",
                            IsActive = true,
                            Key = "dashboard",
                            Order = 1,
                            Route = "/",
                            Title = "داشبورد"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "ShoppingOutlined",
                            IsActive = true,
                            Key = "products",
                            Order = 2,
                            RequiredPermissionCode = "Product.ViewAll",
                            Route = "#",
                            Title = "مدیریت محصولات"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Key = "products-list",
                            Order = 1,
                            ParentId = 2,
                            RequiredPermissionCode = "Product.ViewAll",
                            Route = "/products",
                            Title = "لیست محصولات"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Key = "category-management",
                            Order = 2,
                            ParentId = 2,
                            RequiredPermissionCode = "ProductCategory.Manage",
                            Route = "/product-categories",
                            Title = "مدیریت دسته‌بندی‌ها"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "SettingOutlined",
                            IsActive = true,
                            Key = "settings",
                            Order = 4,
                            RequiredPermissionCode = "Settings.View",
                            Route = "#",
                            Title = "تنظیمات"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Key = "menu-settings",
                            Order = 2,
                            ParentId = 5,
                            RequiredPermissionCode = "Menu.Manage",
                            Route = "/menu-settings",
                            Title = "تنظیمات منو"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "TeamOutlined",
                            IsActive = true,
                            Key = "user-management",
                            Order = 3,
                            RequiredPermissionCode = "User.Manage",
                            Route = "#",
                            Title = "مدیریت کاربران"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Key = "users",
                            Order = 1,
                            ParentId = 6,
                            RequiredPermissionCode = "User.Manage",
                            Route = "/users",
                            Title = "کاربران"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Key = "roles",
                            Order = 2,
                            ParentId = 6,
                            RequiredPermissionCode = "Role.Manage",
                            Route = "/roles",
                            Title = "نقش‌ها"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Key = "permissions",
                            Order = 3,
                            ParentId = 6,
                            RequiredPermissionCode = "Permission.Manage",
                            Route = "/permissions",
                            Title = "دسترسی‌ها"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "TeamOutlined",
                            IsActive = true,
                            Key = "suppliers",
                            Order = 5,
                            RequiredPermissionCode = "Supplier.View",
                            Route = "#",
                            Title = "مدیریت تأمین‌کنندگان"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Key = "supplier-types",
                            Order = 2,
                            ParentId = 11,
                            RequiredPermissionCode = "SupplierType.Manage",
                            Route = "/supplier-types",
                            Title = "مدیریت نوع تأمین‌کننده"
                        });
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Offers.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAtBySupplier")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAtBySystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasTax")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SearchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SearchDateTime");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierUserId");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Offers.OfferDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferDocuments", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Code = "Settings.View",
                            Description = "",
                            DisplayName = "مشاهده تنظیمات",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Code = "User.Manage",
                            Description = "",
                            DisplayName = "مدیریت کاربران",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            Code = "Role.Manage",
                            Description = "",
                            DisplayName = "مدیریت نقش‌ها",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            Code = "Permission.Manage",
                            Description = "",
                            DisplayName = "مدیریت دسترسی‌ها",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            Code = "Menu.Manage",
                            Description = "",
                            DisplayName = "مدیریت منوها",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            Code = "Product.ViewAll",
                            Description = "",
                            DisplayName = "مشاهده محصولات",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            Code = "ProductCategory.Manage",
                            Description = "",
                            DisplayName = "مدیریت دسته‌بندی محصولات",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000008"),
                            Code = "SupplierType.Manage",
                            Description = "",
                            DisplayName = "مدیریت نوع تأمین‌کننده",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000009"),
                            Code = "Supplier.Manage",
                            Description = "",
                            DisplayName = "مدیریت تأمین‌کنندگان",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000a"),
                            Code = "Kyc.Review",
                            Description = "",
                            DisplayName = "بررسی مدارک KYC",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductAttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductAttributeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("ProductId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("ProductAttributeTemplates", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.SupplierCategoryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("UserId", "ProductCategoryId")
                        .IsUnique();

                    b.ToTable("SupplierCategoryAccesses", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "IngAppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            Description = "دسترسی کامل به سیستم",
                            DisplayName = "ادمین",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "دسترسی‌های پایه کاربر",
                            DisplayName = "خریدار",
                            IsActive = true,
                            Name = "Buyer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "دسترسی‌های پنل تأمین‌کننده",
                            DisplayName = "تأمین‌کننده",
                            IsActive = true,
                            Name = "Supplier"
                        });
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermissionId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PermissionId1");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1"),
                            PermissionId = new Guid("aaaaaaaa-0000-0000-0000-00000000000a")
                        });
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdminUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SupplierProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierProfileId");

                    b.ToTable("SupplierActivityLogs");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("SupplierProfiles");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SupplierTypes", (string)null);
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierVerificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierProfileId");

                    b.ToTable("SupplierVerificationHistories");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64fa4b00-95cf-4a58-6f40-08de38f0e8e0"),
                            CreatedAt = new DateTime(2025, 12, 20, 1, 20, 18, 865, DateTimeKind.Utc).AddTicks(7843),
                            DisplayName = "علی هور",
                            IsActive = true,
                            PhoneNumber = "09123823632",
                            SubscriptionLevel = 0,
                            UserType = 3,
                            VerificationStatus = 0
                        });
                });

            modelBuilder.Entity("KycTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("KycAttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SupplierTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KycAttributeDefinitionId");

                    b.ToTable("KycTemplates", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("64fa4b00-95cf-4a58-6f40-08de38f0e8e0"),
                            RoleId = new Guid("a3f0b7e8-3a42-4b27-a9c4-64e0a91b9fd1")
                        });
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Kyc.UserDocument", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Users.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Menus.MenuItem", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Menus.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Offers.OfferDocument", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Offers.Offer", "Offer")
                        .WithMany("Documents")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Products.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductAttributeTemplate", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Products.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IngApp.Domain.Entities.Products.Product", "Product")
                        .WithMany("AttributeTemplates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Products.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.SupplierCategoryAccess", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Products.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Roles.RolePermission", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IngApp.Domain.Entities.Permissions.Permission", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId1");

                    b.HasOne("IngApp.Domain.Entities.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierActivityLog", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Suppliers.SupplierProfile", "SupplierProfile")
                        .WithMany()
                        .HasForeignKey("SupplierProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierProfile");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierProfile", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Suppliers.SupplierType", "SupplierType")
                        .WithMany()
                        .HasForeignKey("SupplierTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IngApp.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Suppliers.SupplierVerificationHistory", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Suppliers.SupplierProfile", "SupplierProfile")
                        .WithMany()
                        .HasForeignKey("SupplierProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierProfile");
                });

            modelBuilder.Entity("KycTemplate", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Kyc.KycAttributeDefinition", "KycAttributeDefinition")
                        .WithMany()
                        .HasForeignKey("KycAttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KycAttributeDefinition");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("IngApp.Domain.Entities.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IngApp.Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Menus.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Offers.Offer", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Permissions.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("AttributeTemplates");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IngApp.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
